development:
  adapter: postgresql
  encoding: unicode
  database: sdok_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: sdok_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: sdok_production
  pool: 5
